@ECHO OFF
SET APP_NAME=PORTFOLIO V.1.0 ALPHA 
TITLE %APP_NAME% 


color 0F
ECHO BOOTING...
ECHO BRAIN LOADING...
ECHO ERROR CODE 1
ECHO OPENING...ERROR-1.log 
ECHO ===============================================
ECHO NAME : NAME
ECHO NICKNAME : NICKNAME
ECHO E_MAIL : YOUREMAIL
ECHO TEL : YOURPASSWORD
ECHO ================================================
pause
